NATURES = {
  rent: [
    'Ampli',
    'Adaptateur international',
    'Appareil à fondue',
    'Appareil à raclette',
    'Aspirateur',
    'Barbecue',
    'Bâtons de ski',
    'Béquilles',
    'Berceau',
    'Bombe (équitation)',
    'Chaises pliantes',
    'Chauffage d\'appoint',
    'Chauffe biberon',
    'Chevillère',
    'Clubs de golf',
    'Console de jeu',
    'Déambulateur',
    'Echarpe (médical)',
    'Enceintes',
    'Escabeau',
    'Fauteuil roulant',
    'Fer à repasser',
    'Genouillère',
    'Imprimante',
    'Jumelles',
    'Kitchen Aid',
    'Landeau',
    'Lit parapluie',
    'Long board',
    'Manettes de console',
    'Narguilé',
    'Stroboscope',
    'Wakeboard',
    'Visseuse',
    'Manteau de ski',
    'Combinaison de ski',
    'Micro',
    'Microscope',
    'Minerve',
    'Mixeur',
    'Oeuvre d\'art',
    'Perceuse',
    'Pinces crocodile',
    'Planche à repasser',
    'Planche de surf',
    'Platines de DJ',
    'Poussette',
    'Raquette (tennis)',
    'Raquette (tennis de table)',
    'Raquettes (neige)',
    'Rollers',
    'Rouleau à peinture',
    'Sac à dos',
    'Sac à main',
    'Sac de voyage',
    'Scanner',
    'Selle (équitation)',
    'Siège bébé',
    'Siège enfant',
    'Shaker',
    'Skateboard',
    'Skis alpins',
    'Snowboard',
    'Skis de fond',
    'Trottinette',
    'Téléscope',
    'Tente',
    'Vélo',
    'Ventilateur',
    'Vidéoprojecteur',
    'Trousse de secours',
    'Cocotte',
    'Caméra',
    'GoPro',
    'Tondeuse',
    'Souffleuse à feuilles',
    'Machine à café',
    'Guitare électrique',
    'Guitare',
    'Synthétiseur',
    'Haltères',
    'Shampooineuse à moquette',
    'Luge',
    'Equipement (polo)',
    'Equipement (football)',
    'Equipement (football américain)',
    'Equipement (basketball)',
    'Equipement (tennis)',
    'Equipement (plongée)',
    'Equipement (ski)',
    'Equipement (pêche)',
    'Canne à pêche',
    'Valise',
    'Fer à friser',
    'Fer à lisser',
    'Machine à coudre',
    'Sac de couchage',
    'Tapis de sol',
    'Diable',
    'Chariot élévateur',
    'Coffre de toit',
    'Casque (moto)',
    'Casque (intégral)',
    'Casque (scooter)',
    'Casque (vélo)',
    'Casque (skateboard)',
    'Déguisement',
    'Costume',
    'Smoking',
    'Robe de soirée',
    'Lunettes de soleil',
    'Bijoux',
    'Appareil photo',
    'Pierrade',
    'Plancha',
    'Tabouret',
    'Fauteuil',
    'Table',
    'Matelas gonflable',
    'Chauffeuse',
    'Tréteaux',
    'Broyeur',
    'Appareil à gaufres',
    'Appareil à panini',
    'Rice cooker',
    'Friteuse',
    'Crépière',
    'Machine à hotdog',
    'Machine à pain',
    'Fontaine à chocolat',
    'Syphon',
    'Plat à tajine',
    'Couscoussière',
    'Machine à pop corn',
    'Machine à barbe à papa',
    'Bombonne à hélium',
    'Tourne-disque',
    'Lecteur blu-ray',
    'Lecteur DVD',
    'Jeu de société',
    'Caisse à outils',
    'Ponceuse',
    'Scie circulaire',
    'Pistolet à peinture',
    'Cireuse à chaussures',
    'Cireuse de sol',
    'Epilateur éléctrique',
    'Epilateur à cire',
    'Steamer',
    'Nettoyeur haute pression',
    'Taille-haie',
    'Bêche',
    'Sécateur',
    'Table abdominaux',
    'Jacuzzi de pieds',
    'Chaussures (randonnée)',
    'Chaussures (ski)',
    'Chaussures (moon boots)',
    'Masque (montagne)',
    'Masque (mer)',
    'Tuba',
    'Palmes',
    'Chauffe-eau',
    'Ustensiles de cuisine',
    'Magnétoscope (VHS)',
    'Hachoir'
  ],

  service: [
    'Baby-sitting',
    'Ménage',
    'Repassage',
    'Faire le linge',
    'Pet-sitting',
    'Pet-feeding',
    'Conciergerie',
    'Covoiturage',
    'Faire les courses',
    'Faire le marché',
    'Massage à domicile',
    'Accompagner les enfants',
    'Faire la cuisine',
    'Aide au déménagement',
    'Laver la voiture',
    'Bricolage léger',
    'Plomberie légère',
    'Tenir compagnie aux personnes âgées'
  ]
}
