NATURES = {
  rent: [
    'Ampli',
    'Adaptateur international',
    'Appareil à fondue',
    'Appareil à raclette',
    'Aspirateur',
    'Barbecue',
    'Bâtons de ski',
    'Béquilles',
    'Berceau',
    'Bombe (équitation)',
    'Chaises pliantes',
    'Chauffage d\'appoint',
    'Chauffe biberon',
    'Chevillère',
    'Clubs de golf',
    'Console de jeux',
    'Déambulateur',
    'Echarpe (médical)',
    'Enceintes',
    'Escabeau',
    'Fauteuil roulant',
    'Fer à repasser',
    'Genouillère',
    'Imprimante',
    'Jumelles',
    'Kitchen Aid',
    'Landau',
    'Lit parapluie',
    'Long board',
    'Manettes de console',
    'Narguilé',
    'Stroboscope',
    'Wakeboard',
    'Visseuse',
    'Manteau de ski',
    'Combinaison de ski',
    'Micro',
    'Microscope',
    'Minerve',
    'Mixeur',
    'Oeuvre d\'art',
    'Perceuse',
    'Pinces crocodile',
    'Planche à repasser',
    'Planche de surf',
    'Platines de DJ',
    'Poussette',
    'Raquette (tennis)',
    'Raquette (tennis de table)',
    'Raquettes (neige)',
    'Rollers',
    'Rouleau à peinture',
    'Sac à dos',
    'Sac à main',
    'Sac de voyage',
    'Scanner',
    'Selle (équitation)',
    'Siège bébé',
    'Siège enfant',
    'Shaker',
    'Skateboard',
    'Skis alpins',
    'Snowboard',
    'Skis de fond',
    'Trottinette',
    'Téléscope',
    'Tente',
    'Vélo',
    'Ventilateur',
    'Vidéoprojecteur',
    'Trousse de secours',
    'Cocotte',
    'Caméra',
    'GoPro',
    'Tondeuse',
    'Souffleuse à feuilles',
    'Machine à café',
    'Guitare électrique',
    'Guitare',
    'Synthétiseur',
    'Haltères',
    'Shampooineuse à moquette',
    'Luge',
    'Equipement (polo)',
    'Equipement (football)',
    'Equipement (football américain)',
    'Equipement (basketball)',
    'Equipement (tennis)',
    'Equipement (plongée)',
    'Equipement (ski)',
    'Equipement (pêche)',
    'Canne à pêche',
    'Valise',
    'Fer à friser',
    'Fer à lisser',
    'Machine à coudre',
    'Sac de couchage',
    'Tapis de sol',
    'Diable',
    'Chariot élévateur',
    'Coffre de toit',
    'Casque (moto)',
    'Casque (intégral)',
    'Casque (scooter)',
    'Casque (vélo)',
    'Casque (skateboard)',
    'Déguisement',
    'Costume',
    'Smoking',
    'Robe de soirée',
    'Lunettes de soleil',
    'Bijoux',
    'Appareil photo',
    'Pierrade',
    'Plancha',
    'Tabouret',
    'Fauteuil',
    'Table',
    'Matelas gonflable',
    'Chauffeuse',
    'Tréteaux',
    'Broyeur',
    'Appareil à gaufres',
    'Appareil à panini',
    'Rice cooker',
    'Friteuse',
    'Crépière',
    'Machine à hotdog',
    'Machine à pain',
    'Fontaine à chocolat',
    'Syphon',
    'Plat à tajine',
    'Couscoussière',
    'Machine à pop corn',
    'Machine à barbe à papa',
    'Bombonne à hélium',
    'Tourne-disque',
    'Lecteur blu-ray',
    'Lecteur DVD',
    'Jeu de société',
    'Caisse à outils',
    'Ponceuse',
    'Scie circulaire',
    'Pistolet à peinture',
    'Cireuse à chaussures',
    'Cireuse de sol',
    'Epilateur éléctrique',
    'Epilateur à cire',
    'Steamer',
    'Nettoyeur haute pression',
    'Taille-haie',
    'Bêche',
    'Sécateur',
    'Table abdominaux',
    'Jacuzzi de pieds',
    'Chaussures (randonnée)',
    'Chaussures (ski)',
    'Chaussures (moon boots)',
    'Masque (montagne)',
    'Masque (mer)',
    'Tuba',
    'Palmes',
    'Bouilloire',
    'Ustensiles de cuisine',
    'Magnétoscope (VHS)',
    'Hachoir',
    'Seau à champagne',
    'Cuiseur vapeur',
    'Centrifugeuse',
    'Boules de pétanque',
    'Malette de poker'
  ],
  service: [
    'Baby-sitting',
    'Ménage',
    'Repassage',
    'Faire le linge',
    'Pet-sitting',
    'Pet-feeding',
    'Conciergerie',
    'Covoiturage',
    'Faire les courses',
    'Faire le marché',
    'Massage à domicile',
    'Accompagner les enfants',
    'Faire la cuisine',
    'Aide au déménagement',
    'Laver la voiture',
    'Bricolage léger',
    'Plomberie légère',
    'Tenir compagnie aux personnes âgées',
    'Jardinage',
    'Arroser les plantes',
    'Coaching sportif',
    'Soutien scolaire',
    'Dépannage informatique'
  ],
  en: {
    rent: [
      'Amp',
      'International adapter',
      'Fondue set',
      'Raclette set',
      'Vacuum cleaner',
      'Barbecue',
      'Ski poles',
      'Crutches',
      'Cradle',
      'Helmet (horse riding)',
      'Folding chair',
      'Heating unit',
      'Bottle warmer',
      'Ankle brace',
      'Golf clubs',
      'Game console',
      'Rollator',
      'Arm sling',
      'Speakers',
      'Step ladder',
      'Wheelchair',
      'Iron',
      'Rompers',
      'Printer',
      'Binoculars',
      'Kitchen Aid',
      'Stroller',
      'Baby bed',
      'Long board',
      'Console controller',
      'Hookah',
      'Stroboscope',
      'Wakeboard',
      'Screwer',
      'Ski jacket',
      'Ski suit',
      'Microphone',
      'Microscope',
      'Neck brace',
      'Mixer',
      'Work of art',
      'Drill',
      'Crocodile clip',
      'Ironing board',
      'Surf board',
      'Turntable',
      'Buggy',
      'Tennis racket',
      'Table tennis paddle',
      'Snowshoes',
      'Roller skates',
      'Paint roller',
      'Backpack',
      'Purse',
      'Travel bag',
      'Desktop scanner',
      'Saddle',
      'Baby seat',
      'Child seat',
      'Cocktail shaker',
      'Skateboard',
      'Alpin Skis',
      'Snowboard',
      'Cross country skis',
      'Scooter',
      'Telescope',
      'Tent',
      'Bike',
      'Fan',
      'Projector',
      'First aid kit',
      'Casserole',
      'Camera (video)',
      'GoPro',
      'Trimmer',
      'Leaf blower',
      'Coffee machine',
      'Electric guitare',
      'Guitare',
      'Synthetizer',
      'Dumbbells',
      'Carpet cleaner',
      'Luge',
      'Equipment (polo)',
      'Equipment (soccer)',
      'Equipment (football américain)',
      'Equipment (basketball)',
      'Equipment (tennis)',
      'Equipment (scuba diving)',
      'Equipment (ski)',
      'Equipment (fishing)',
      'Fishing stick',
      'Suitcase',
      'Curling iron',
      'Hair straitghtner',
      'Sewing machine',
      'Sleeping bag',
      'Floor mat',
      'Troley',
      'Loader',
      'Roof box',
      'Helmet (motocycle)',
      'Helmet (full face)',
      'Helmet (scooter)',
      'Helmet (bike)',
      'Helmet (skateboard)',
      'Costume',
      'Suit',
      'Tuxedo',
      'Party dress',
      'Sunglasses',
      'Jewelry',
      'Camera',
      'Stone grill',
      'Plancha',
      'Stool',
      'Armchair',
      'Table',
      'Inflatable mattress',
      'Fireside chair',
      'Trestles',
      'Shredder',
      'Waffle maker',
      'Panini toaster',
      'Rice cooker',
      'Fryer',
      'Pancake pan',
      'Hotdog machine',
      'Bread machine',
      'Chocolat fountain',
      'Syphon',
      'Tajine plate',
      'Couscous maker',
      'Popcorn machine',
      'Cotton candy machine',
      'Helium gas tank',
      'Record player',
      'Blu-ray player',
      'DVD player',
      'Board games',
      'Toolbox',
      'Grinding machine',
      'Circular saw',
      'Spray paint gun',
      'Shoe shine machine',
      'Polishing machine',
      'Electric depilator',
      'Wax depilator',
      'Steamer',
      'High pressure cleaner',
      'Hedge trimmer',
      'Spade',
      'Pruning shear',
      'Abdominal board',
      'Foot spa',
      'Shoes (hiking)',
      'Shoes (ski)',
      'Shoes (moon boots)',
      'Ski mask (montagne)',
      'Mask (diving)',
      'Tuba',
      'Flippers',
      'Kettle',
      'Kitchen utensils',
      'Video recorder (VCR)',
      'Food chopper',
      'Champagne bucket',
      'Steam cooker',
      'Centrifuge',
      'Petanque set',
      'Poker set'
    ],

    service: [
      'Baby-sitting',
      'Cleaning',
      'Ironing',
      'Do the laundry',
      'Pet-sitting',
      'Pet-feeding',
      'Concierge services',
      'Carpool',
      'Run errands',
      'Go to the market',
      'Massages',
      'Accompany Children',
      'Cooking',
      'Handyman help for moves',
      'Washing cars',
      'Easy handiwork',
      'Light plumbing',
      'Keeping the elderly company',
      'Gardening',
      'Watering plants',
      'Coaching (sports) ',
      'Schooling support',
      'Computer troubleshooting'
    ]
  }
}
